#启动接口
server:
  port: 8848

#数据源配置
spring:
  datasource:
    # druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000

  #JPA相关配置
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    show-sql: false #这里开启sql打印
    hibernate:
      ddl-auto: none #程序启动时删除并创建实体类对应的那个表（危险）


#配置mybatis
mybatis-plus:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations:
    - classpath:mybatis/mappers/**/*.xml                    # mapper映射文件

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时(毫秒)
  expiration: 7200000
  #token 活跃用户刷新时间30分钟刷新(毫秒)
  refreshToken: 1800000
  # 在线用户key
  online: online-token
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info

rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==
default:
  password: Pass_123

lock:
  #允许登录失败次数
  count: 5
  #锁定用户key
  lockKey: lock-user
  #1分钟内分钟内
  expiration: 60
  #锁定时长(秒)-15分钟
  lockTime: 900

#单一登录
single:
  login: false
  #是否验证验证码
  vCode: false

# 文件存储路径
dir:
  framework: framework
  business: virtualdir.war
file:
  path: D:\webaffixdir\
  framework: ${file.path}\${dir.framework}\
  business: ${file.path}\${dir.business}\
  # 文件大小 /M
  frameworkMaxSize: 100
  businessMaxSize: 2048